export const characters = [
  {
    id: 1,
    name: "캐릭터 A",
    role: "주인공",
    initial: "A",
    age: "??세",
    gender: "—",
    height: "—",
    desc: "여기에 캐릭터 소개를 입력하세요.",
    color: "#1e1e30",
    accent: "#AFA9EC",
  },
  {
    id: 2,
    name: "캐릭터 B",
    role: "동료",
    initial: "B",
    age: "??세",
    gender: "—",
    height: "—",
    desc: "여기에 캐릭터 소개를 입력하세요.",
    color: "#1a1e1a",
    accent: "#5DCAA5",
  },
  {
    id: 3,
    name: "캐릭터 C",
    role: "라이벌",
    initial: "C",
    age: "??세",
    gender: "—",
    height: "—",
    desc: "여기에 캐릭터 소개를 입력하세요.",
    color: "#1e1a1a",
    accent: "#F0997B",
  },
  {
    id: 4,
    name: "캐릭터 D",
    role: "조력자",
    initial: "D",
    age: "??세",
    gender: "—",
    height: "—",
    desc: "여기에 캐릭터 소개를 입력하세요.",
    color: "#1a1a1e",
    accent: "#85B7EB",
  },
  {
    id: 5,
    name: "캐릭터 E",
    role: "조력자",
    initial: "E",
    age: "??세",
    gender: "—",
    height: "—",
    desc: "여기에 캐릭터 소개를 입력하세요.",
    color: "#1e1a1e",
    accent: "#ED93B1",
  },
  {
    id: 6,
    name: "캐릭터 F",
    role: "적대",
    initial: "F",
    age: "??세",
    gender: "—",
    height: "—",
    desc: "여기에 캐릭터 소개를 입력하세요.",
    color: "#1e1a18",
    accent: "#EF9F27",
  },
]

export const worldCards = [
  { icon: "ti-world",           title: "세계관",    desc: "시대적 배경, 마법 체계나 기술 수준 등을 담을 수 있어요." },
  { icon: "ti-building-castle", title: "주요 세력", desc: "등장하는 주요 세력이나 집단에 대한 설명을 적어두세요." },
  { icon: "ti-sparkles",        title: "규칙과 설정", desc: "세계의 법칙, 특이한 규칙, 독특한 설정 등을 정리하는 공간이에요." },
  { icon: "ti-map-pin",         title: "주요 장소", desc: "이야기에서 중요하게 등장하는 장소들을 소개하는 란이에요." },
]
